project:
  type: default

format:
  html:
    code-fold: true
    code-summary: "Afficher le code source Python"
    theme: cosmo
    toc: false
    embed-resources: false
    plotly-connected: true
    css: collapse-sections.css
    include-after-body: collapse-sections.html